#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Common_CONSTANTS_H_1
#define Common_CONSTANTS_H_1

#include "Common_types.h"

namespace emq { namespace common {

class CommonConstants {
 public:
  CommonConstants();

  std::map<ErrorCode::type, int64_t>  ERROR_BACKOFF;
  std::map<ErrorCode::type, RetryType::type>  ERROR_RETRY_TYPE;
  int32_t MAX_RETRY;
};

extern const CommonConstants g_Common_constants;

}} // namespace

#endif
