#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Constants_CONSTANTS_H
#define Constants_CONSTANTS_H

#include "Constants_types.h"

namespace emq { namespace constants {

class ConstantsConstants {
 public:
  ConstantsConstants();

  int32_t DEFAULT_CLIENT_SOCKET_TIMEOUT;
  int32_t DEFAULT_CLIENT_CONN_TIMEOUT;
  std::string DEFAULT_SERVICE_ENDPOINT;
  std::string DEFAULT_SECURE_SERVICE_ENDPOINT;
  std::string QUEUE_SERVICE_PATH;
  std::string MESSAGE_SERVICE_PATH;
  std::string STATISTICS_SERVICE_PATH;
  std::string XIAOMI_HEADER_PREFIX;
  std::string MI_DATE;
  std::string GALAXY_ACCESS_KEY_ID;
  std::string SIGNATURE;
  std::string AUTHORIZATION;
  std::string CONTENT_MD5;
  std::string CONTENT_TYPE;
  std::string DATE;
  std::string RANGE;
  std::string USER_AGENT;
  std::string HOST;
  std::string TIMESTAMP;
  std::string CONTENT_LENGTH;
};

extern const ConstantsConstants g_Constants_constants;

}} // namespace

#endif
