#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Message_CONSTANTS_H
#define Message_CONSTANTS_H

#include "Message_types.h"

namespace emq { namespace message {

class MessageConstants {
 public:
  MessageConstants();

};

extern const MessageConstants g_Message_constants;

}} // namespace

#endif
