/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Message_constants.h"

namespace emq { namespace message {

const MessageConstants g_Message_constants;

MessageConstants::MessageConstants() {
}

}} // namespace

