#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Queue_CONSTANTS_H
#define Queue_CONSTANTS_H

#include "Queue_types.h"

namespace emq { namespace queue {

class QueueConstants {
 public:
  QueueConstants();

};

extern const QueueConstants g_Queue_constants;

}} // namespace

#endif
