/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Statistics_constants.h"

namespace emq { namespace statistics {

const StatisticsConstants g_Statistics_constants;

StatisticsConstants::StatisticsConstants() {
}

}} // namespace

