#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Admin_CONSTANTS_H
#define Admin_CONSTANTS_H

#include "Admin_types.h"



class AdminConstants {
 public:
  AdminConstants();

};

extern const AdminConstants g_Admin_constants;



#endif
