#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Authentication_CONSTANTS_H
#define Authentication_CONSTANTS_H

#include "Authentication_types.h"



class AuthenticationConstants {
 public:
  AuthenticationConstants();

  std::map<UserType::type, bool>  SIGNATURE_SUPPORT;
  std::string HK_AUTHORIZATION;
  std::string HK_HOST;
  std::string HK_TIMESTAMP;
  std::string HK_CONTENT_MD5;
  std::string HK_VERSION;
  std::string HK_USER_TYPE;
  std::string HK_SECRET_KEY_ID;
  std::string HK_SECRET_KEY;
  std::string HK_SIGNATURE;
  std::string HK_MAC_ALGORITHM;
  std::string HK_SUPPORT_ACCOUNT_KEY;
  std::vector<std::string>  SUGGESTED_SIGNATURE_HEADERS;
};

extern const AuthenticationConstants g_Authentication_constants;



#endif
