#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SLFile_CONSTANTS_H
#define SLFile_CONSTANTS_H

#include "SLFile_types.h"



class SLFileConstants {
 public:
  SLFileConstants();

};

extern const SLFileConstants g_SLFile_constants;



#endif
