/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Authorization_constants.h"

namespace rpc { namespace authorization {

const AuthorizationConstants g_Authorization_constants;

AuthorizationConstants::AuthorizationConstants() {
}

}} // namespace

