#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Authentication_CONSTANTS_H
#define Authentication_CONSTANTS_H

#include "Authentication_types.h"

namespace rpc { namespace auth {

class AuthenticationConstants {
 public:
  AuthenticationConstants();

  std::map<UserType::type, bool>  SIGNATURE_SUPPORT;
  std::string HK_HOST;
  std::string HK_TIMESTAMP;
  std::string MI_DATE;
  std::string XIAOMI_HEADER_PREFIX;
  std::string HK_CONTENT_MD5;
  std::string HK_AUTHORIZATION;
  std::string HK_SERVICE_ADMIN;
  std::string HK_SERVICE_MARK;
  std::string HK_ATTACHED_INFO;
  std::vector<std::string>  SUGGESTED_SIGNATURE_HEADERS;
};

extern const AuthenticationConstants g_Authentication_constants;

}} // namespace

#endif
