/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Common_constants.h"

namespace rpc { namespace common {

const CommonConstants g_Common_constants;

CommonConstants::CommonConstants() {
  DEFAULT_CLIENT_TIMEOUT = 10000;

  DEFAULT_MAX_CLIENT_TIMEOUT = 10000;

  DEFAULT_ADMIN_CLIENT_TIMEOUT = 30000;

  DEFAULT_CLIENT_CONN_TIMEOUT = 3000;

  API_ROOT_PATH = "/v1/api";

  AUTH_SERVICE_PATH = "/v1/api/auth";

  ADMIN_SERVICE_PATH = "/v1/api/admin";

  DEFAULT_THRIFT_HEADER = "application/x-thrift";

  THRIFT_JSON_HEADER = "application/x-thrift-json";

  THRIFT_COMPACT_HEADER = "application/x-thrift-compact";

  THRIFT_BINARY_HEADER = "application/x-thrift-binary";

  THRIFT_HEADER_MAP.insert(std::make_pair((ThriftProtocol::type)0, "application/x-thrift-compact"));
  THRIFT_HEADER_MAP.insert(std::make_pair((ThriftProtocol::type)1, "application/x-thrift-json"));
  THRIFT_HEADER_MAP.insert(std::make_pair((ThriftProtocol::type)2, "application/x-thrift-binary"));

  HEADER_THRIFT_MAP.insert(std::make_pair("application/x-thrift-compact", (ThriftProtocol::type)0));
  HEADER_THRIFT_MAP.insert(std::make_pair("application/x-thrift-json", (ThriftProtocol::type)1));
  HEADER_THRIFT_MAP.insert(std::make_pair("application/x-thrift-binary", (ThriftProtocol::type)2));
  HEADER_THRIFT_MAP.insert(std::make_pair("application/x-thrift", (ThriftProtocol::type)1));

  HK_REQUEST_TIMEOUT = "X-Xiaomi-Request-Timeout";

  HK_ERROR_CODE_HEADER = "X-Xiaomi-Error-Code";

  MAX_CONTENT_SIZE = 524288;

}

}} // namespace

