#include "../client/undefine.h"
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Errors_CONSTANTS_H
#define Errors_CONSTANTS_H

#include "Errors_types.h"

namespace rpc { namespace errors {

class ErrorsConstants {
 public:
  ErrorsConstants();

  std::map<ErrorCode::type, int64_t>  ERROR_BACKOFF;
  std::map<ErrorCode::type, RetryType::type>  ERROR_RETRY_TYPE;
  int32_t MAX_RETRY;
};

extern const ErrorsConstants g_Errors_constants;

}} // namespace

#endif
