/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Errors_constants.h"

namespace rpc { namespace errors {

const ErrorsConstants g_Errors_constants;

ErrorsConstants::ErrorsConstants() {
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)2, 1000LL));
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)25, 1000LL));
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)37, 0LL));
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)32, 0LL));
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)1, 1000LL));
  ERROR_BACKOFF.insert(std::make_pair((ErrorCode::type)35, 1000LL));

  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)2, (RetryType::type)0));
  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)25, (RetryType::type)0));
  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)37, (RetryType::type)0));
  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)32, (RetryType::type)0));
  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)1, (RetryType::type)1));
  ERROR_RETRY_TYPE.insert(std::make_pair((ErrorCode::type)35, (RetryType::type)1));

  MAX_RETRY = 1;

}

}} // namespace

